name: "bytebase"

services:
  bytebase:
    image: bytebase/bytebase:latest
    container_name: bytebase
    restart: unless-stopped
    ports:
      - "${PORT_BYTEBASE}:8080"
    volumes:
      - type: bind
        source: ${VOLUME_DATA_DIR}/bytebase/data
        target: /var/opt/bytebase
        read_only: false
    environment:
      - PG_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_DB_HOST}:5432/${POSTGRES_DB}
    depends_on:
      - bytebase-db

  bytebase-db:
    image: postgres:18
    container_name: bytebase-db
    hostname: ${POSTGRES_DB_HOST}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/18/docker
    volumes:
      - type: bind
        source: ${VOLUME_DATA_DIR}/bytebase/db
        target: /var/lib/postgresql
        read_only: false
