name: "comfyui-cachy-01"

services:
  comfyui:
    image: yanwk/comfyui-boot:cu130-slim@sha256:064155b374686ac4862a063fa3ac6dd6742dad80d638def3cdc28a2fecb6b21b
    container_name: comfyui
    restart: unless-stopped
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - ${PUBLIC_PORT}:8188
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8188/system_stats"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - ${VOLUME_DATA_DIR}/comfyui/ComfyUI:/root/ComfyUI
      - ${VOLUME_DATA_DIR}/comfyui/cache:/root/.cache
      - ${EXTERNAL_VOLUME_DATA_DIR}/settings_for_cachyos/ComfyUI/output:/root/ComfyUI/output
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CLI_ARGS=--disable-xformers
