name: "memos-staging"

services:
  memos-staging:
    image: neosmemo/memos:stable
    container_name: memos-staging
    hostname: memos
    user: "${PUID}:${PGID}"
    volumes:
      - type: bind
        source: ${VOLUME_DATA_DIR}/memos/data
        target: /var/opt/memos
        read_only: false
    network_mode: host
    environment:
      - PORT=5241
      - MEMOS_DRIVER=postgres
      - MEMOS_DSN='postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_DB_HOST}:5432/memos?sslmode=disable'
    restart: on-failure:5
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5241/
    depends_on:
      db:
        condition: service_healthy
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "memos-staging"
      tsdproxy.container_port: 5241

  db:
    image: postgres:18
    container_name: memos-db
    hostname: ${POSTGRES_DB_HOST}
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "memos", "-U", "${POSTGRES_USER}"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - type: bind
        source: ${VOLUME_DATA_DIR}/memos/db
        target: /var/lib/postgresql
        read_only: false
    environment:
      POSTGRES_DB: memos
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    restart: on-failure:5
