set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -s escape-time 50
set -g default-shell "${SHELL}"
set -g history-limit 10000
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

setw -g status-style fg="colour15",bg="colour30"

set -g status-left-length 30
set -g status-left '#[fg=colour0,bg=colour26] #S '

set -g status-right-length 60
set -g status-right '#[fg=colour0,bg=colour248] %Y-%m-%d %H:%M #[fg=colour0,bg=colour26] #h '

set -g mouse on
setw -g window-status-separator " "
setw -g window-status-format '#[fg=colour0,bg=colour248] #I: #W '
setw -g window-status-current-format '#[fg=colour248,bg=colour165] #I: #W '

setw -g mode-style fg="colour248",bg="colour165"

set -g pane-border-style fg="colour248"
set -g pane-active-border-style fg="colour165"

set -g window-style 'bg=colour237'
set -g window-active-style 'bg=terminal'

bind r source-file ~/.config/tmux/tmux.conf \; display "config reloaded!"

bind \\ split-window -h
