set -g  default-terminal "xterm-256color"
set -ga terminal-overrides ",$TERM:Tc"
set -g  default-shell "${SHELL}"
set -g  history-limit 10000
set -g  escape-time 10
set -g  base-index 1
set -g  pane-base-index 1

setw -g status-style fg="colour0",bg="colour45"

set -g mouse on
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
setw -g window-status-style fg="colour0",bg="colour154"
setw -g window-status-current-style fg="colour0",bg="colour207"
setw -g window-status-separator "  "

setw -g mode-style fg="colour0",bg="colour207"
