name: dockhand

services:
  dockhand:
    image: fnsys/dockhand:v1.0.20
    container_name: dockhand
    restart: unless-stopped
    ports:
      - 3100:3000
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: ${VOLUME_DATA_DIR}/data
        target: /app/data
