name: "komga"

services:
  komga:
    image: gotson/komga
    container_name: komga
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 5<>/dev/tcp/127.0.0.1/25600"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - type: bind
        source: ${VOLUME_DATA_DIR}/komga/config
        target: /config
      - type: bind
        source: ${VOLUME_DATA_DIR}/komga/data
        target: /data
    environment:
      - TZ=Asia/Tokyo
    restart: unless-stopped
    ports:
      - ${PUBLIC_PORT}:25600
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "komga"
      tsdproxy.container_port: ${PUBLIC_PORT}
